language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  app: draumateymid
  api_key:
    secure: mPH58jiedbcXqMHMup3sEFJgRp9GfkU1wRjixcz3D3zj6TH9GkiMxKPHzMcdOOxaiLxTjAD/0hXK4vEQgbrHlb0zmogGJH1lMffxla1xocg/X1kz2C80BUNz04iDmHUjfkS6hhH3j/Ea1Bu9O057zV8lWxeaQeoGVXQ2FFI2iGH05S5Yg8mOG+EkPbo6NFm6NX1NxvpaxgG+13me14feXyQWbqFtPa/KNfZf7iJZJtiSWiXma4QePTs52+6K6aRtk5hZHqbmKdwN1Gvyt2F8YX6ScgJhyyAwxP4lMyEEhMPHzrFJ0C7XDSHA2IzI5QpMYOg9sGHxhvWAGvdZR85Ghp2hlBDmbsQy2Hj5DDi4u+pVuwBvftVxFZpZ/9Zr4rq3ZHR2Tta2r8JCarj5If/z5SFm6KcR5QHmZ7DIHOSMgKWxROCSUw0glGKWDZqPnkv2b61y9nK7Faj6f/vHcgjw5JJQgqhb4DG6hs1MZICFrwgkVv1kfqXALUvCNHuXj2EyKMQXEtZOBC26UJMG/Ky2xf2h/J8vzNglLN9TJ1n46eba8EnwZF+Ht8gurjBYOWjiXK5oeTjyeM31BN2uUOYkHmQcmmhRkzY3M7ftJ1krTKlgXeu2g/5yirXq3iyl0PX7bsBrdPzm5OqmHH6B9wmI5j2+AL0gtMei+qNs7ftnuz0=
