/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'aguste13' at '10/18/16 8:18 PM' with Gradle 3.1
 *
 * @author aguste13, @date 10/18/16 8:18 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
